### ISSUE TITLE
Not pulling from recent messages

### ISSUE THREAD

**Issue by Johnhall90** [claabs/markov-discord#16]
Hi, I am having trouble managing to get any recent messages into the corpus. When I train, it seems like it it only pulling from older messages closer to the beginning of the text channel. I have tried spamming specific words that do not show up when running !mark.

**Comment by claabs** [comment]
The corpus is scheduled to regenerate daily at [4 AM local time](https://github.com/claabs/markov-discord/blob/master/index.ts#L420). You can also manually regenerate the corpus using `!mark regen`. Are you manually regenerating the corpus in your testing?

**Comment by claabs** [comment]
I guess I should also ask for clarification on this: Do the messages that you expect to show up exist before the train, or are you sending them after the training.

Also if you're just spamming one word, the markov chain will have trouble adding it to a message since it joins together messages that have common word(s) and space separators.

**Comment by Johnhall90** [comment]
I have tried the regen command as well as training quite often. But I think you mentioning the spamming individual words might be what I was doing wrong. I'll try making more structured sentences and see what happens. Thank you for the help!

**Comment by claabs** [comment]
Also try out `!mark debug` to get a better idea of how it scores and assembles messages.
